### ISSUE TITLE
doesn't work on the last version of nodejs

### ISSUE THREAD

**Issue by mickae1** [pushrax/node-xdcc#7]
Hi, can you tell me on which version of nodejs it's working ? because on the last one there is problem during the install  ( windows 10 )

**Comment by pushrax** [comment]
Can you include the log indicating the problem?

**Comment by mickae1** [comment]
c:\node_modules\nan\nan.h(590): error C2039: 'GCEpilogueCallback' : n'est pas membre de 'v8::Isolate' [c:\node_modules\iconv\build\iconv.vcxproj]

**Comment by mickae1** [comment]
n'est pas membre de = is not a member of

**Comment by pushrax** [comment]
This is an upstream issue in node-irc https://github.com/martynsmith/node-irc/issues/463

**Comment by mickae1** [comment]
How to fix it?

**Comment by Tsarpf** [comment]
I got node-irc working with node 4.
